export const EMPLOYEES_LOADING="EMPLOYEES_LOADING";
export const EMPLOYEES_LOAD_EMPLOYEE="EMPLOYEES_LOAD_EMPLOYEE";
export const EMPLOYEES_LOAD_ERROR="EMPLOYEES_LOAD_ERROR";

export const ADD_EMPLOYEES_LOADING="ADD_EMPLOYEES_LOADING";
export const ADD_EMPLOYEES_LOAD_SUCCES="ADD_EMPLOYEES_LOAD_SUCCES";
export const ADD_EMPLOYEES_LOAD_ERROR="ADD_EMPLOYEES_LOAD_ERROR";
export const CLEAR_ADD_EMPLOYEE="CLEAR_ADD_EMPLOYEE";
export const EDIT_EMPLOYEES_LOADING="EDIT_EMPLOYEES_LOADING";
export const EDIT_EMPLOYEES_LOAD_SUCCES="EDIT_EMPLOYEES_LOAD_SUCCES";
export const EDIT_EMPLOYEES_LOAD_ERROR="EDIT_EMPLOYEES_LOAD_ERROR";
export const CLEAR_EDIT_EMPLOYEE="CLEAR_EDIT_EMPLOYEE";

export const DELETE_EMPLOYEE_LOADING="DELETE_EMPLOYEE_LOADING";
export const DELETE_EMPLOYEE_SUCCESS="DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_ERROR="DELETE_EMPLOYEE_ERROR";


 
export const DEPARTMENTS_LOADING="DEPARTMENTS_LOADING";
export const DEPARTMENTS_LOAD_DEPARTMENT="DEPARTMENTS_LOAD_DEPARTMENT";
export const DEPARTMENTS_LOAD_ERROR="DEPARTMENTS_LOAD_ERROR";

export const ADD_DEPARTMENTS_LOADING="ADD_DEPARTMENTS_LOADING";
export const ADD_DEPARTMENTS_LOAD_SUCCES="ADD_DEPARTMENTS_LOAD_SUCCES";
export const ADD_DEPARTMENTS_LOAD_ERROR="ADD_DEPARTMENTS_LOAD_ERROR";
export const CLEAR_ADD_DEPARTMENT="CLEAR_ADD_DEPARTMENT";
export const EDIT_DEPARTMENTS_LOADING="EDIT_DEPARTMENTS_LOADING";
export const EDIT_DEPARTMENTS_LOAD_SUCCES="EDIT_DEPARTMENTS_LOAD_SUCCES";
export const EDIT_DEPARTMENTS_LOAD_ERROR="EDIT_DEPARTMENTS_LOAD_ERROR";
export const CLEAR_EDIT_DEPARTMENT="CLEAR_EDIT_DEPARTMENT";

export const DELETE_DEPARTMENT_LOADING="DELETE_DEPARTMENT_LOADING";
export const DELETE_DEPARTMENT_SUCCESS="DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_ERROR="DELETE_DEPARTMENT_ERROR";



export const LOGIN_LOADING="LOGIN_LOADING";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_ERROR="LOGIN_ERROR";


export const SIGNUP_LOADING="SIGNUP_LOADING";
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
export const SIGNUP_ERROR="SIGNUP_ERROR";


export const EditProfile_LOADING="EditProfile_LOADING";
export const EditProfile_SUCCESS="EditProfile_SUCCESS";
export const EditProfile_ERROR="EditProfile_ERROR";



export const ROLES_LOADING="ROLES_LOADING";
export const ROLES_LOAD_ROLE="ROLES_LOAD_ROLE";
export const ROLES_LOAD_ERROR="ROLES_LOAD_ERROR";

export const ADD_ROLES_LOADING="ADD_ROLES_LOADING";
export const ADD_ROLES_LOAD_SUCCES="ADD_ROLES_LOAD_SUCCES";
export const ADD_ROLES_LOAD_ERROR="ADD_ROLES_LOAD_ERROR";
export const CLEAR_ADD_ROLE="CLEAR_ADD_ROLE";
export const EDIT_ROLES_LOADING="EDIT_ROLES_LOADING";
export const EDIT_ROLES_LOAD_SUCCES="EDIT_ROLES_LOAD_SUCCES";
export const EDIT_ROLES_LOAD_ERROR="EDIT_ROLES_LOAD_ERROR";
export const CLEAR_EDIT_ROLE="CLEAR_EDIT_ROLE";

export const DELETE_ROLE_LOADING="DELETE_ROLE_LOADING";
export const DELETE_ROLE_SUCCESS="DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_ERROR="DELETE_ROLE_ERROR";







export const GET_EMPDEP_LOADING="GET_EMPDEP_LOADING";
export const GET_EMPDEP_SUCCESS="GET_EMPDEP_SUCCESS";
export const GET_EMPDEP_ERROR="GET_EMPDEP_ERROR";







